### ISSUE TITLE
Change README

### ISSUE THREAD

**Issue by WebBreacher** [DeadS3c/WhatsMyName#1]
Just popped over to check out your new code! Very exciting. Noticed that your README shows `pip install requirements.txt` but your requirements file is actually named `requisites.txt` and you need the `-r` flag. May I suggest you change your README to be `pip install -r requisites.txt`?

**Comment by bash-bunny** [comment]
Hey thank you!!
I totally misspelled that, correcting it right now.
And yes, it should be `pip install -r requirements.txt`
